/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.purejosh.pureores.init;

import net.purejosh.pureores.item.SapphireSwordItem;
import net.purejosh.pureores.item.SapphireShovelItem;
import net.purejosh.pureores.item.SapphirePickaxeItem;
import net.purejosh.pureores.item.SapphireItem;
import net.purejosh.pureores.item.SapphireHoeItem;
import net.purejosh.pureores.item.SapphireAxeItem;
import net.purejosh.pureores.item.SapphireArmorItem;
import net.purejosh.pureores.item.MoonstoneSwordItem;
import net.purejosh.pureores.item.MoonstoneShovelItem;
import net.purejosh.pureores.item.MoonstonePickaxeItem;
import net.purejosh.pureores.item.MoonstoneItem;
import net.purejosh.pureores.item.MoonstoneHoeItem;
import net.purejosh.pureores.item.MoonstoneAxeItem;
import net.purejosh.pureores.item.MoonstoneArmorItem;
import net.purejosh.pureores.item.LonsdaleiteSwordItem;
import net.purejosh.pureores.item.LonsdaleiteShovelItem;
import net.purejosh.pureores.item.LonsdaleitePickaxeItem;
import net.purejosh.pureores.item.LonsdaleiteItem;
import net.purejosh.pureores.item.LonsdaleiteHoeItem;
import net.purejosh.pureores.item.LonsdaleiteAxeItem;
import net.purejosh.pureores.item.LonsdaleiteArmorItem;
import net.purejosh.pureores.item.JadeiteSwordItem;
import net.purejosh.pureores.item.JadeiteShovelItem;
import net.purejosh.pureores.item.JadeitePickaxeItem;
import net.purejosh.pureores.item.JadeiteItem;
import net.purejosh.pureores.item.JadeiteHoeItem;
import net.purejosh.pureores.item.JadeiteAxeItem;
import net.purejosh.pureores.item.JadeiteArmorItem;
import net.purejosh.pureores.item.FireOpalSwordItem;
import net.purejosh.pureores.item.FireOpalShovelItem;
import net.purejosh.pureores.item.FireOpalPickaxeItem;
import net.purejosh.pureores.item.FireOpalItem;
import net.purejosh.pureores.item.FireOpalHoeItem;
import net.purejosh.pureores.item.FireOpalAxeItem;
import net.purejosh.pureores.item.FireOpalArmorItem;
import net.purejosh.pureores.item.ChrysoberylSwordItem;
import net.purejosh.pureores.item.ChrysoberylShovelItem;
import net.purejosh.pureores.item.ChrysoberylPickaxeItem;
import net.purejosh.pureores.item.ChrysoberylItem;
import net.purejosh.pureores.item.ChrysoberylHoeItem;
import net.purejosh.pureores.item.ChrysoberylAxeItem;
import net.purejosh.pureores.item.ChrysoberylArmorItem;
import net.purejosh.pureores.item.BlackDiamondSwordItem;
import net.purejosh.pureores.item.BlackDiamondShovelItem;
import net.purejosh.pureores.item.BlackDiamondPickaxeItem;
import net.purejosh.pureores.item.BlackDiamondItem;
import net.purejosh.pureores.item.BlackDiamondHoeItem;
import net.purejosh.pureores.item.BlackDiamondAxeItem;
import net.purejosh.pureores.item.BlackDiamondArmorItem;
import net.purejosh.pureores.item.AmetrineSwordItem;
import net.purejosh.pureores.item.AmetrineShovelItem;
import net.purejosh.pureores.item.AmetrinePickaxeItem;
import net.purejosh.pureores.item.AmetrineItem;
import net.purejosh.pureores.item.AmetrineHoeItem;
import net.purejosh.pureores.item.AmetrineAxeItem;
import net.purejosh.pureores.item.AmetrineArmorItem;
import net.purejosh.pureores.PureoresMod;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;

public class PureoresModItems {
	public static Item MOONSTONE;
	public static Item FIRE_OPAL;
	public static Item JADEITE;
	public static Item AMETRINE;
	public static Item CHRYSOBERYL;
	public static Item SAPPHIRE;
	public static Item BLACK_DIAMOND;
	public static Item LONSDALEITE;
	public static Item MOONSTONE_BLOCK;
	public static Item FIRE_OPAL_BLOCK;
	public static Item JADEITE_BLOCK;
	public static Item AMETRINE_BLOCK;
	public static Item CHRYSOBERYL_BLOCK;
	public static Item SAPPHIRE_BLOCK;
	public static Item BLACK_DIAMOND_BLOCK;
	public static Item LONSDALEITE_BLOCK;
	public static Item MOONSTONE_SHOVEL;
	public static Item MOONSTONE_PICKAXE;
	public static Item MOONSTONE_AXE;
	public static Item MOONSTONE_HOE;
	public static Item FIRE_OPAL_SHOVEL;
	public static Item FIRE_OPAL_PICKAXE;
	public static Item FIRE_OPAL_AXE;
	public static Item FIRE_OPAL_HOE;
	public static Item JADEITE_SHOVEL;
	public static Item JADEITE_PICKAXE;
	public static Item JADEITE_AXE;
	public static Item JADEITE_HOE;
	public static Item AMETRINE_SHOVEL;
	public static Item AMETRINE_PICKAXE;
	public static Item AMETRINE_AXE;
	public static Item AMETRINE_HOE;
	public static Item CHRYSOBERYL_SHOVEL;
	public static Item CHRYSOBERYL_PICKAXE;
	public static Item CHRYSOBERYL_AXE;
	public static Item CHRYSOBERYL_HOE;
	public static Item SAPPHIRE_SHOVEL;
	public static Item SAPPHIRE_PICKAXE;
	public static Item SAPPHIRE_AXE;
	public static Item SAPPHIRE_HOE;
	public static Item BLACK_DIAMOND_SHOVEL;
	public static Item BLACK_DIAMOND_PICKAXE;
	public static Item BLACK_DIAMOND_AXE;
	public static Item BLACK_DIAMOND_HOE;
	public static Item LONSDALEITE_SHOVEL;
	public static Item LONSDALEITE_PICKAXE;
	public static Item LONSDALEITE_AXE;
	public static Item LONSDALEITE_HOE;
	public static Item MOONSTONE_SWORD;
	public static Item MOONSTONE_HELMET;
	public static Item MOONSTONE_CHESTPLATE;
	public static Item MOONSTONE_LEGGINGS;
	public static Item MOONSTONE_BOOTS;
	public static Item FIRE_OPAL_SWORD;
	public static Item FIRE_OPAL_HELMET;
	public static Item FIRE_OPAL_CHESTPLATE;
	public static Item FIRE_OPAL_LEGGINGS;
	public static Item FIRE_OPAL_BOOTS;
	public static Item JADEITE_SWORD;
	public static Item JADEITE_HELMET;
	public static Item JADEITE_CHESTPLATE;
	public static Item JADEITE_LEGGINGS;
	public static Item JADEITE_BOOTS;
	public static Item AMETRINE_SWORD;
	public static Item AMETRINE_HELMET;
	public static Item AMETRINE_CHESTPLATE;
	public static Item AMETRINE_LEGGINGS;
	public static Item AMETRINE_BOOTS;
	public static Item CHRYSOBERYL_SWORD;
	public static Item CHRYSOBERYL_HELMET;
	public static Item CHRYSOBERYL_CHESTPLATE;
	public static Item CHRYSOBERYL_LEGGINGS;
	public static Item CHRYSOBERYL_BOOTS;
	public static Item SAPPHIRE_SWORD;
	public static Item SAPPHIRE_HELMET;
	public static Item SAPPHIRE_CHESTPLATE;
	public static Item SAPPHIRE_LEGGINGS;
	public static Item SAPPHIRE_BOOTS;
	public static Item BLACK_DIAMOND_SWORD;
	public static Item BLACK_DIAMOND_HELMET;
	public static Item BLACK_DIAMOND_CHESTPLATE;
	public static Item BLACK_DIAMOND_LEGGINGS;
	public static Item BLACK_DIAMOND_BOOTS;
	public static Item LONSDALEITE_SWORD;
	public static Item LONSDALEITE_HELMET;
	public static Item LONSDALEITE_CHESTPLATE;
	public static Item LONSDALEITE_LEGGINGS;
	public static Item LONSDALEITE_BOOTS;
	public static Item MOONSTONE_ORE;
	public static Item NETHER_FIRE_OPAL_ORE;
	public static Item SERPENTINITE_STONE;
	public static Item JADEITE_ORE;
	public static Item END_AMETRINE_ORE;
	public static Item MICA_SCHIST;
	public static Item CHRYSOBERYL_ORE;
	public static Item SAPPHIRE_ORE;
	public static Item DEEPSLATE_BLACK_DIAMOND_ORE;
	public static Item LONSDALEITE_METEORITE_STONE;
	public static Item LONSDALEITE_ORE;

	public static void load() {
		MOONSTONE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone"), new MoonstoneItem());
		FIRE_OPAL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal"), new FireOpalItem());
		JADEITE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite"), new JadeiteItem());
		AMETRINE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine"), new AmetrineItem());
		CHRYSOBERYL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl"), new ChrysoberylItem());
		SAPPHIRE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire"), new SapphireItem());
		BLACK_DIAMOND = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond"), new BlackDiamondItem());
		LONSDALEITE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite"), new LonsdaleiteItem());
		MOONSTONE_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_block"), new BlockItem(PureoresModBlocks.MOONSTONE_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.BUILDING_BLOCKS).register(content -> content.accept(MOONSTONE_BLOCK));
		FIRE_OPAL_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_block"), new BlockItem(PureoresModBlocks.FIRE_OPAL_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.BUILDING_BLOCKS).register(content -> content.accept(FIRE_OPAL_BLOCK));
		JADEITE_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_block"), new BlockItem(PureoresModBlocks.JADEITE_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.BUILDING_BLOCKS).register(content -> content.accept(JADEITE_BLOCK));
		AMETRINE_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_block"), new BlockItem(PureoresModBlocks.AMETRINE_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.BUILDING_BLOCKS).register(content -> content.accept(AMETRINE_BLOCK));
		CHRYSOBERYL_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_block"), new BlockItem(PureoresModBlocks.CHRYSOBERYL_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.BUILDING_BLOCKS).register(content -> content.accept(CHRYSOBERYL_BLOCK));
		SAPPHIRE_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_block"), new BlockItem(PureoresModBlocks.SAPPHIRE_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.BUILDING_BLOCKS).register(content -> content.accept(SAPPHIRE_BLOCK));
		BLACK_DIAMOND_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_block"), new BlockItem(PureoresModBlocks.BLACK_DIAMOND_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.BUILDING_BLOCKS).register(content -> content.accept(BLACK_DIAMOND_BLOCK));
		LONSDALEITE_BLOCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_block"), new BlockItem(PureoresModBlocks.LONSDALEITE_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.BUILDING_BLOCKS).register(content -> content.accept(LONSDALEITE_BLOCK));
		MOONSTONE_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_shovel"), new MoonstoneShovelItem());
		MOONSTONE_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_pickaxe"), new MoonstonePickaxeItem());
		MOONSTONE_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_axe"), new MoonstoneAxeItem());
		MOONSTONE_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_hoe"), new MoonstoneHoeItem());
		FIRE_OPAL_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_shovel"), new FireOpalShovelItem());
		FIRE_OPAL_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_pickaxe"), new FireOpalPickaxeItem());
		FIRE_OPAL_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_axe"), new FireOpalAxeItem());
		FIRE_OPAL_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_hoe"), new FireOpalHoeItem());
		JADEITE_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_shovel"), new JadeiteShovelItem());
		JADEITE_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_pickaxe"), new JadeitePickaxeItem());
		JADEITE_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_axe"), new JadeiteAxeItem());
		JADEITE_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_hoe"), new JadeiteHoeItem());
		AMETRINE_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_shovel"), new AmetrineShovelItem());
		AMETRINE_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_pickaxe"), new AmetrinePickaxeItem());
		AMETRINE_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_axe"), new AmetrineAxeItem());
		AMETRINE_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_hoe"), new AmetrineHoeItem());
		CHRYSOBERYL_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_shovel"), new ChrysoberylShovelItem());
		CHRYSOBERYL_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_pickaxe"), new ChrysoberylPickaxeItem());
		CHRYSOBERYL_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_axe"), new ChrysoberylAxeItem());
		CHRYSOBERYL_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_hoe"), new ChrysoberylHoeItem());
		SAPPHIRE_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_shovel"), new SapphireShovelItem());
		SAPPHIRE_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_pickaxe"), new SapphirePickaxeItem());
		SAPPHIRE_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_axe"), new SapphireAxeItem());
		SAPPHIRE_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_hoe"), new SapphireHoeItem());
		BLACK_DIAMOND_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_shovel"), new BlackDiamondShovelItem());
		BLACK_DIAMOND_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_pickaxe"), new BlackDiamondPickaxeItem());
		BLACK_DIAMOND_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_axe"), new BlackDiamondAxeItem());
		BLACK_DIAMOND_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_hoe"), new BlackDiamondHoeItem());
		LONSDALEITE_SHOVEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_shovel"), new LonsdaleiteShovelItem());
		LONSDALEITE_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_pickaxe"), new LonsdaleitePickaxeItem());
		LONSDALEITE_AXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_axe"), new LonsdaleiteAxeItem());
		LONSDALEITE_HOE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_hoe"), new LonsdaleiteHoeItem());
		MOONSTONE_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_sword"), new MoonstoneSwordItem());
		MOONSTONE_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_helmet"), new MoonstoneArmorItem.Helmet());
		MOONSTONE_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_chestplate"), new MoonstoneArmorItem.Chestplate());
		MOONSTONE_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_leggings"), new MoonstoneArmorItem.Leggings());
		MOONSTONE_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_boots"), new MoonstoneArmorItem.Boots());
		FIRE_OPAL_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_sword"), new FireOpalSwordItem());
		FIRE_OPAL_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_helmet"), new FireOpalArmorItem.Helmet());
		FIRE_OPAL_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_chestplate"), new FireOpalArmorItem.Chestplate());
		FIRE_OPAL_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_leggings"), new FireOpalArmorItem.Leggings());
		FIRE_OPAL_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "fire_opal_boots"), new FireOpalArmorItem.Boots());
		JADEITE_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_sword"), new JadeiteSwordItem());
		JADEITE_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_helmet"), new JadeiteArmorItem.Helmet());
		JADEITE_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_chestplate"), new JadeiteArmorItem.Chestplate());
		JADEITE_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_leggings"), new JadeiteArmorItem.Leggings());
		JADEITE_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_boots"), new JadeiteArmorItem.Boots());
		AMETRINE_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_sword"), new AmetrineSwordItem());
		AMETRINE_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_helmet"), new AmetrineArmorItem.Helmet());
		AMETRINE_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_chestplate"), new AmetrineArmorItem.Chestplate());
		AMETRINE_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_leggings"), new AmetrineArmorItem.Leggings());
		AMETRINE_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "ametrine_boots"), new AmetrineArmorItem.Boots());
		CHRYSOBERYL_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_sword"), new ChrysoberylSwordItem());
		CHRYSOBERYL_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_helmet"), new ChrysoberylArmorItem.Helmet());
		CHRYSOBERYL_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_chestplate"), new ChrysoberylArmorItem.Chestplate());
		CHRYSOBERYL_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_leggings"), new ChrysoberylArmorItem.Leggings());
		CHRYSOBERYL_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_boots"), new ChrysoberylArmorItem.Boots());
		SAPPHIRE_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_sword"), new SapphireSwordItem());
		SAPPHIRE_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_helmet"), new SapphireArmorItem.Helmet());
		SAPPHIRE_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_chestplate"), new SapphireArmorItem.Chestplate());
		SAPPHIRE_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_leggings"), new SapphireArmorItem.Leggings());
		SAPPHIRE_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_boots"), new SapphireArmorItem.Boots());
		BLACK_DIAMOND_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_sword"), new BlackDiamondSwordItem());
		BLACK_DIAMOND_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_helmet"), new BlackDiamondArmorItem.Helmet());
		BLACK_DIAMOND_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_chestplate"), new BlackDiamondArmorItem.Chestplate());
		BLACK_DIAMOND_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_leggings"), new BlackDiamondArmorItem.Leggings());
		BLACK_DIAMOND_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "black_diamond_boots"), new BlackDiamondArmorItem.Boots());
		LONSDALEITE_SWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_sword"), new LonsdaleiteSwordItem());
		LONSDALEITE_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_helmet"), new LonsdaleiteArmorItem.Helmet());
		LONSDALEITE_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_chestplate"), new LonsdaleiteArmorItem.Chestplate());
		LONSDALEITE_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_leggings"), new LonsdaleiteArmorItem.Leggings());
		LONSDALEITE_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_boots"), new LonsdaleiteArmorItem.Boots());
		MOONSTONE_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "moonstone_ore"), new BlockItem(PureoresModBlocks.MOONSTONE_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(MOONSTONE_ORE));
		NETHER_FIRE_OPAL_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "nether_fire_opal_ore"), new BlockItem(PureoresModBlocks.NETHER_FIRE_OPAL_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(NETHER_FIRE_OPAL_ORE));
		SERPENTINITE_STONE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "serpentinite_stone"), new BlockItem(PureoresModBlocks.SERPENTINITE_STONE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(SERPENTINITE_STONE));
		JADEITE_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "jadeite_ore"), new BlockItem(PureoresModBlocks.JADEITE_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(JADEITE_ORE));
		END_AMETRINE_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "end_ametrine_ore"), new BlockItem(PureoresModBlocks.END_AMETRINE_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(END_AMETRINE_ORE));
		MICA_SCHIST = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "mica_schist"), new BlockItem(PureoresModBlocks.MICA_SCHIST, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(MICA_SCHIST));
		CHRYSOBERYL_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "chrysoberyl_ore"), new BlockItem(PureoresModBlocks.CHRYSOBERYL_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(CHRYSOBERYL_ORE));
		SAPPHIRE_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "sapphire_ore"), new BlockItem(PureoresModBlocks.SAPPHIRE_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(SAPPHIRE_ORE));
		DEEPSLATE_BLACK_DIAMOND_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "deepslate_black_diamond_ore"), new BlockItem(PureoresModBlocks.DEEPSLATE_BLACK_DIAMOND_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(DEEPSLATE_BLACK_DIAMOND_ORE));
		LONSDALEITE_METEORITE_STONE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_meteorite_stone"), new BlockItem(PureoresModBlocks.LONSDALEITE_METEORITE_STONE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(LONSDALEITE_METEORITE_STONE));
		LONSDALEITE_ORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureoresMod.MODID, "lonsdaleite_ore"), new BlockItem(PureoresModBlocks.LONSDALEITE_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(LONSDALEITE_ORE));
	}

	public static void clientLoad() {
	}
}
